name: Maven Deploy

on:
  release:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout maven repository
        #      env:
        #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        FIRST_NAME: Mona
        #        LAST_NAME: Octocat
        uses: actions/checkout@v4


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: 'maven'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B deploy -Ddeploy.dir=mvn-repo --file pom.xml


      - name: Push changes
      - uses: actions/checkout@v4
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "${{ github.repository}} ${{ github.ref }} deployed"
          git push

